### ISSUE TITLE
NPM install

### ISSUE THREAD

**Issue by mauron85** [MSOpenTech/cordova-plugin-indexedDB#11]
Cannot install your plugin, because in plugin.xml package name is cordova-plugin-indexedDB, but in package.json cordova-plugin-indexeddb. 

```
Fetching plugin "cordova-plugin-indexeddb" via npm
Failed to install 'cordova-plugin-mauron85-background-geolocation':Error: Expected plugin to have ID "cordova-plugin-indexeddb" but got "cordova-plugin-indexedDB".
    at checkID (/Users/finch/.nvm/versions/node/v0.12.7/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:177:15)
    at /Users/finch/.nvm/versions/node/v0.12.7/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:161:9
    at _fulfilled (/Users/finch/.nvm/versions/node/v0.12.7/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/finch/.nvm/versions/node/v0.12.7/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/finch/.nvm/versions/node/v0.12.7/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /Users/finch/.nvm/versions/node/v0.12.7/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/Users/finch/.nvm/versions/node/v0.12.7/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
Error: Expected plugin to have ID "cordova-plugin-indexeddb" but got "cordova-plugin-indexedDB".
    at checkID (/Users/finch/.nvm/versions/node/v0.12.7/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:177:15)
    at /Users/finch/.nvm/versions/node/v0.12.7/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:161:9
    at _fulfilled (/Users/finch/.nvm/versions/node/v0.12.7/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/finch/.nvm/versions/node/v0.12.7/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/finch/.nvm/versions/node/v0.12.7/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /Users/finch/.nvm/versions/node/v0.12.7/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/Users/finch/.nvm/versions/node/v0.12.7/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
```

**Comment by theavijitsarkar** [comment]
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.msopentech.indexeddb
